// ======================================================
// PHASE 5.4 — PAYROLL EXPORT ENGINE
//
// Pure functions. No side effects. No React state.
// All data flows from PayrollStagingRecord[] which are
// produced by groupTimesheetsForPayroll() in profitabilityEngine.ts.
//
// Doctrine:
//   Approved TimesheetEntry records
//   → groupTimesheetsForPayroll()  (profitabilityEngine.ts)
//   → PayrollStagingRecord[]       (draft staging)
//   → generatePayrollExport()      ← this file
//   → PayrollExport                (exportable payload)
//   → CSV download / downstream payroll system
//
// Never: Job → Payroll directly.
// Never: re-derive hours from raw ReviewItem data.
// Always: consume from the approved TimesheetEntry layer.
// ======================================================

import type { PayrollStagingRecord } from "@/lib/profitabilityEngine";

// ──────────────────────────────────────────────────────
// TYPE: PayrollPeriod
//
// Describes the payroll period for a given export run.
// Either a bounded window (start → end) or 'all-time'.
// ──────────────────────────────────────────────────────
export type PayrollPeriodType = "all" | "current-month" | "last-month" | "custom";

export interface PayrollPeriod {
  type: PayrollPeriodType;
  startDate: string | null;  // ISO string or null for 'all'
  endDate: string | null;    // ISO string or null for 'all'
  label: string;             // Human-readable e.g. "May 2026" or "All approved timesheets"
}

// ──────────────────────────────────────────────────────
// TYPE: PayrollExportStatus
//
// Tracks the lifecycle of a generated payroll export.
//   generated → downloaded → exported
//
// 'generated' — export payload created, not yet downloaded
// 'downloaded' — file downloaded by user
// 'exported' — confirmed sent to payroll system (manual)
// ──────────────────────────────────────────────────────
export type PayrollExportStatus = "generated" | "downloaded" | "exported";

// ──────────────────────────────────────────────────────
// TYPE: PayrollWorkerSummary
//
// Per-worker line in the export payload.
// Mirrors PayrollStagingRecord but is a self-contained
// snapshot — safe to serialise and transmit downstream
// without reference to other application state.
// ──────────────────────────────────────────────────────
export interface PayrollWorkerSummary {
  workerId: string;
  workerName: string;
  totalHours: number;
  totalCost: number;           // labour cost (business pays)
  totalRevenue: number;        // labour revenue (billed to client)
  margin: number;              // (revenue - cost) / revenue * 100
  timesheetCount: number;      // number of TimesheetEntry records included
  jobIds: string[];            // distinct jobs this worker has hours on
  jobLabels: string[];         // resolved job titles (or jobId if unresolvable)
}

// ──────────────────────────────────────────────────────
// TYPE: PayrollExport
//
// The complete, self-contained payroll export document.
// Generated by generatePayrollExport() and stored in
// mockPayrollExports[].
//
// This is an audit-grade document — once generated its
// payload is immutable. Any re-generation creates a new
// export with a new ID and timestamp.
// ──────────────────────────────────────────────────────
export interface PayrollExport {
  id: string;
  exportNumber: string;         // e.g. "PAY-2026-0001"
  period: PayrollPeriod;
  workers: PayrollWorkerSummary[];

  // Totals — derived from workers[] on generation
  totalWorkers: number;
  totalHours: number;
  totalCost: number;
  totalRevenue: number;
  overallMargin: number;        // totalRevenue > 0 ? (totalRevenue - totalCost) / totalRevenue * 100 : 0

  status: PayrollExportStatus;
  generatedAt: string;          // ISO — when generatePayrollExport() was called
  generatedBy: string;          // user name

  // Validation
  validationErrors: string[];   // populated if export has issues (empty = valid)
  isValid: boolean;             // true if validationErrors.length === 0
}

// ──────────────────────────────────────────────────────
// derivePeriodBounds
//
// Converts a PayrollPeriodType into concrete start/end
// ISO strings and a human-readable label.
//
// Used both by the UI (to compute filter bounds for
// groupTimesheetsForPayroll) and by the export engine
// (to stamp the PayrollPeriod on the export document).
// ──────────────────────────────────────────────────────
export function derivePeriodBounds(type: PayrollPeriodType, customStart?: string, customEnd?: string): PayrollPeriod {
  const now = new Date();

  if (type === "all") {
    return {
      type,
      startDate: null,
      endDate: null,
      label: "All approved timesheets",
    };
  }

  if (type === "current-month") {
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    return {
      type,
      startDate: start.toISOString(),
      endDate: now.toISOString(),
      label: start.toLocaleString("en-GB", { month: "long", year: "numeric" }),
    };
  }

  if (type === "last-month") {
    const start = new Date(now.getFullYear(), now.getMonth() - 1, 1);
    const end = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59);
    return {
      type,
      startDate: start.toISOString(),
      endDate: end.toISOString(),
      label: start.toLocaleString("en-GB", { month: "long", year: "numeric" }),
    };
  }

  // custom
  const startDate = customStart ?? null;
  const endDate = customEnd ?? null;
  const startLabel = startDate
    ? new Date(startDate).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
    : "—";
  const endLabel = endDate
    ? new Date(endDate).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
    : "—";
  return {
    type,
    startDate,
    endDate,
    label: `${startLabel} – ${endLabel}`,
  };
}

// ──────────────────────────────────────────────────────
// validatePayrollExport
//
// Pure validation. Returns an array of error strings.
// Empty array = valid. Non-empty array = invalid.
//
// Validates:
//   - Export must have at least one worker
//   - All workers must have totalHours > 0
//   - All workers must have totalCost >= 0
//   - Period must be defined (either bounded or all-time)
// ──────────────────────────────────────────────────────
export function validatePayrollExport(workers: PayrollWorkerSummary[], period: PayrollPeriod): string[] {
  const errors: string[] = [];

  if (workers.length === 0) {
    errors.push("No approved timesheet records found for the selected period.");
  }

  workers.forEach((w) => {
    if (w.totalHours <= 0) {
      errors.push(`Worker "${w.workerName}" has zero or negative hours (${w.totalHours}h). Review timesheet data.`);
    }
    if (w.totalCost < 0) {
      errors.push(`Worker "${w.workerName}" has a negative labour cost. Review rate data.`);
    }
  });

  return errors;
}

// ──────────────────────────────────────────────────────
// generatePayrollExport
//
// Creates a PayrollExport from an array of PayrollStagingRecord[].
// The staging records are produced by groupTimesheetsForPayroll()
// in profitabilityEngine.ts — this engine does not re-aggregate
// timesheet data itself.
//
// Parameters:
//   id          — caller-supplied unique ID
//   exportNumber — e.g. "PAY-2026-0001" from generateExportNumber()
//   records     — PayrollStagingRecord[] from groupTimesheetsForPayroll()
//   period      — PayrollPeriod from derivePeriodBounds()
//   jobLookup   — map of jobId → job title for label resolution
//   generatedBy — current user's name
//
// Returns a fully-computed, immutable PayrollExport.
// ──────────────────────────────────────────────────────
export function generatePayrollExport(
  id: string,
  exportNumber: string,
  records: PayrollStagingRecord[],
  period: PayrollPeriod,
  jobLookup: Map<string, string>,
  generatedBy: string,
): PayrollExport {
  // Map PayrollStagingRecord → PayrollWorkerSummary
  const workers: PayrollWorkerSummary[] = records.map((r) => ({
    workerId: r.workerId,
    workerName: r.workerName,
    totalHours: r.totalHours,
    totalCost: r.totalCost,
    totalRevenue: r.totalRevenue,
    margin: r.margin,
    timesheetCount: r.timesheetIds.length,
    jobIds: r.jobIds,
    jobLabels: r.jobIds.map((jid) => jobLookup.get(jid) ?? jid),
  }));

  // Aggregate totals
  const totalWorkers = workers.length;
  const totalHours = workers.reduce((s, w) => s + w.totalHours, 0);
  const totalCost = workers.reduce((s, w) => s + w.totalCost, 0);
  const totalRevenue = workers.reduce((s, w) => s + w.totalRevenue, 0);
  const overallMargin = totalRevenue > 0
    ? ((totalRevenue - totalCost) / totalRevenue) * 100
    : 0;

  const validationErrors = validatePayrollExport(workers, period);

  return {
    id,
    exportNumber,
    period,
    workers,
    totalWorkers,
    totalHours,
    totalCost,
    totalRevenue,
    overallMargin,
    status: "generated",
    generatedAt: new Date().toISOString(),
    generatedBy,
    validationErrors,
    isValid: validationErrors.length === 0,
  };
}

// ──────────────────────────────────────────────────────
// serializePayrollExportToCSV
//
// Converts a PayrollExport into a CSV string suitable for
// download. Format is designed for import into standard
// payroll and accounting systems.
//
// Columns:
//   Worker ID, Worker Name, Total Hours, Labour Cost (£),
//   Labour Revenue (£), Margin (%), Timesheet Count,
//   Jobs, Period, Export Number, Generated At
// ──────────────────────────────────────────────────────
export function serializePayrollExportToCSV(payrollExport: PayrollExport): string {
  const headers = [
    "Worker ID",
    "Worker Name",
    "Total Hours",
    "Labour Cost (£)",
    "Labour Revenue (£)",
    "Margin (%)",
    "Timesheet Count",
    "Jobs",
    "Period",
    "Export Number",
    "Generated At",
  ];

  const escapeCSV = (value: string | number): string => {
    const str = String(value);
    // Wrap in quotes if contains comma, quote, or newline
    if (str.includes(",") || str.includes('"') || str.includes("\n")) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const rows = payrollExport.workers.map((w) => [
    escapeCSV(w.workerId),
    escapeCSV(w.workerName),
    escapeCSV(w.totalHours.toFixed(2)),
    escapeCSV(w.totalCost.toFixed(2)),
    escapeCSV(w.totalRevenue.toFixed(2)),
    escapeCSV(w.margin.toFixed(2)),
    escapeCSV(w.timesheetCount),
    escapeCSV(w.jobLabels.join("; ")),
    escapeCSV(payrollExport.period.label),
    escapeCSV(payrollExport.exportNumber),
    escapeCSV(new Date(payrollExport.generatedAt).toLocaleString("en-GB")),
  ]);

  const lines = [
    headers.map(escapeCSV).join(","),
    ...rows.map((row) => row.join(",")),
    // Summary row
    "",
    `TOTAL,,${payrollExport.totalHours.toFixed(2)},${payrollExport.totalCost.toFixed(2)},${payrollExport.totalRevenue.toFixed(2)},${payrollExport.overallMargin.toFixed(2)},,,,,`,
  ];

  return lines.join("\n");
}

// ──────────────────────────────────────────────────────
// EXPORT STATUS LABELS & COLORS
// Used in UI components — matches Ledger badge conventions
// ──────────────────────────────────────────────────────

export const EXPORT_STATUS_LABELS: Record<PayrollExportStatus, string> = {
  generated: "Generated",
  downloaded: "Downloaded",
  exported: "Exported",
};

export const EXPORT_STATUS_COLORS: Record<PayrollExportStatus, string> = {
  generated: "text-amber-600  border-amber-200  bg-amber-50",
  downloaded: "text-blue-600   border-blue-200   bg-blue-50",
  exported:   "text-emerald-600 border-emerald-200 bg-emerald-50",
};
