import { Layout } from "@/components/layout";
import { useStore } from "@/lib/mockData";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Clock,
  Receipt,
  Package,
  Wrench,
  FileText,
  Activity,
  DollarSign,
} from "lucide-react";
import { useLocation } from "wouter";

function fmt(n: number) {
  return `£${n.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

const MUTATION_COLORS: Record<string, string> = {
  timesheet: "text-blue-600 border-blue-200 bg-blue-50",
  expense: "text-amber-600 border-amber-200 bg-amber-50",
  inventory: "text-emerald-600 border-emerald-200 bg-emerald-50",
  equipment: "text-violet-600 border-violet-200 bg-violet-50",
  invoice: "text-rose-600 border-rose-200 bg-rose-50",
};

const LINE_TYPE_COLORS: Record<string, string> = {
  labor: "text-blue-600 border-blue-200 bg-blue-50",
  material: "text-emerald-600 border-emerald-200 bg-emerald-50",
  equipment: "text-violet-600 border-violet-200 bg-violet-50",
  expense: "text-amber-600 border-amber-200 bg-amber-50",
};

function EmptyState({ label }: { label: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
      <Activity className="h-10 w-10 mb-3 opacity-20" />
      <p className="text-sm">{label}</p>
    </div>
  );
}

export default function FinancialExplorerPage() {
  const {
    timesheets,
    expenses,
    inventoryMutations,
    equipmentUsageRecords,
    invoiceLineItems,
    financialMutations,
    jobs,
  } = useStore();
  const [, setLocation] = useLocation();

  const jobName = (jobId: string) =>
    jobs.find((j) => j.id === jobId)?.title ?? jobId;

  const JobLink = ({ jobId }: { jobId: string }) => (
    <button
      onClick={() => setLocation(`/jobs/${jobId}`)}
      className="text-left hover:underline text-blue-600 max-w-[160px] truncate block"
    >
      {jobName(jobId)}
    </button>
  );

  const summaryCards = [
    { label: "Timesheets", count: timesheets.length, icon: Clock, color: "text-blue-600" },
    { label: "Expenses", count: expenses.length, icon: Receipt, color: "text-amber-600" },
    { label: "Inventory Mutations", count: inventoryMutations.length, icon: Package, color: "text-emerald-600" },
    { label: "Equipment Usage", count: equipmentUsageRecords.length, icon: Wrench, color: "text-violet-600" },
    { label: "Invoice Line Items", count: invoiceLineItems.length, icon: FileText, color: "text-rose-600" },
    { label: "Financial Mutations", count: financialMutations.length, icon: DollarSign, color: "text-slate-600" },
  ];

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Financial Explorer</h2>
          <p className="text-muted-foreground mt-1">
            Inspect every financial record generated by the Review Center approval engine.
          </p>
        </div>

        {/* Summary Metrics */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {summaryCards.map(({ label, count, icon: Icon, color }) => (
            <Card key={label}>
              <CardHeader className="pb-1 pt-4 px-4">
                <CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                  {label}
                </CardTitle>
              </CardHeader>
              <CardContent className="px-4 pb-4 flex items-center gap-2">
                <Icon className={`h-5 w-5 flex-shrink-0 ${color}`} />
                <span className="text-2xl font-bold">{count}</span>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Tabs */}
        <Tabs defaultValue="mutations">
          <TabsList className="flex flex-wrap h-auto gap-1">
            <TabsTrigger value="mutations">Audit Log</TabsTrigger>
            <TabsTrigger value="timesheets">Timesheets</TabsTrigger>
            <TabsTrigger value="expenses">Expenses</TabsTrigger>
            <TabsTrigger value="inventory">Inventory</TabsTrigger>
            <TabsTrigger value="equipment">Equipment</TabsTrigger>
            <TabsTrigger value="lineitems">Invoice Lines</TabsTrigger>
          </TabsList>

          {/* ── Financial Mutation Audit Log ── */}
          <TabsContent value="mutations">
            <div className="border rounded-md mt-4">
              {financialMutations.length === 0 ? (
                <EmptyState label="No financial records generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Created At</TableHead>
                      <TableHead>Mutation Type</TableHead>
                      <TableHead>Entity ID</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Source Review</TableHead>
                      <TableHead>Approved By</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...financialMutations].reverse().map((m) => (
                      <TableRow key={m.id}>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(m.createdAt)}
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={MUTATION_COLORS[m.mutationType] ?? ""}
                          >
                            {m.mutationType}
                          </Badge>
                        </TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground">
                          {m.entityId}
                        </TableCell>
                        <TableCell><JobLink jobId={m.jobId} /></TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground">
                          {m.sourceReviewId}
                        </TableCell>
                        <TableCell className="text-sm">{m.approvedBy}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>

          {/* ── Timesheets ── */}
          <TabsContent value="timesheets">
            <div className="border rounded-md mt-4">
              {timesheets.length === 0 ? (
                <EmptyState label="No timesheet records generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Worker</TableHead>
                      <TableHead className="text-right">Hours</TableHead>
                      <TableHead className="text-right">Hourly Rate</TableHead>
                      <TableHead className="text-right">Labour Cost</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Approved By</TableHead>
                      <TableHead>Approved At</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...timesheets].reverse().map((t) => (
                      <TableRow key={t.id}>
                        <TableCell className="font-medium">{t.workerName}</TableCell>
                        <TableCell className="text-right">{t.hours}</TableCell>
                        <TableCell className="text-right">{fmt(t.hourlyRate)}</TableCell>
                        <TableCell className="text-right font-medium">{fmt(t.laborCost)}</TableCell>
                        <TableCell><JobLink jobId={t.jobId} /></TableCell>
                        <TableCell className="text-sm">{t.approvedBy}</TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(t.approvedAt)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>

          {/* ── Expenses ── */}
          <TabsContent value="expenses">
            <div className="border rounded-md mt-4">
              {expenses.length === 0 ? (
                <EmptyState label="No expense records generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Description</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Submitted By</TableHead>
                      <TableHead>Approved By</TableHead>
                      <TableHead>Approved At</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...expenses].reverse().map((e) => (
                      <TableRow key={e.id}>
                        <TableCell className="font-medium">{e.description}</TableCell>
                        <TableCell className="text-right font-medium">{fmt(e.amount)}</TableCell>
                        <TableCell><JobLink jobId={e.jobId} /></TableCell>
                        <TableCell className="text-sm">{e.submittedBy}</TableCell>
                        <TableCell className="text-sm">{e.approvedBy}</TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(e.approvedAt)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>

          {/* ── Inventory Mutations ── */}
          <TabsContent value="inventory">
            <div className="border rounded-md mt-4">
              {inventoryMutations.length === 0 ? (
                <EmptyState label="No inventory mutation records generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Stock Item</TableHead>
                      <TableHead className="text-right">Qty Used</TableHead>
                      <TableHead className="text-right">Unit Cost</TableHead>
                      <TableHead className="text-right">Markup</TableHead>
                      <TableHead className="text-right">Cost Impact</TableHead>
                      <TableHead className="text-right">Revenue Impact</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Approved At</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...inventoryMutations].reverse().map((m) => (
                      <TableRow key={m.id}>
                        <TableCell className="font-medium">{m.stockItemName}</TableCell>
                        <TableCell className="text-right">{m.quantityUsed}</TableCell>
                        <TableCell className="text-right">{fmt(m.unitCost)}</TableCell>
                        <TableCell className="text-right">{fmt(m.markupPrice)}</TableCell>
                        <TableCell className="text-right text-red-600 font-medium">
                          {fmt(m.jobCostImpact)}
                        </TableCell>
                        <TableCell className="text-right text-emerald-600 font-medium">
                          {fmt(m.revenueImpact)}
                        </TableCell>
                        <TableCell><JobLink jobId={m.jobId} /></TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(m.approvedAt)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>

          {/* ── Equipment Usage ── */}
          <TabsContent value="equipment">
            <div className="border rounded-md mt-4">
              {equipmentUsageRecords.length === 0 ? (
                <EmptyState label="No equipment usage records generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Asset</TableHead>
                      <TableHead className="text-right">Hours Used</TableHead>
                      <TableHead className="text-right">Usage Cost</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Approved At</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...equipmentUsageRecords].reverse().map((r) => (
                      <TableRow key={r.id}>
                        <TableCell className="font-medium">{r.assetName}</TableCell>
                        <TableCell className="text-right">{r.hoursUsed}</TableCell>
                        <TableCell className="text-right font-medium">
                          {r.usageCost === 0 ? (
                            <span className="text-muted-foreground text-xs">No rate</span>
                          ) : (
                            fmt(r.usageCost)
                          )}
                        </TableCell>
                        <TableCell><JobLink jobId={r.jobId} /></TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(r.approvedAt)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>

          {/* ── Invoice Line Items ── */}
          <TabsContent value="lineitems">
            <div className="border rounded-md mt-4">
              {invoiceLineItems.length === 0 ? (
                <EmptyState label="No invoice line items generated yet." />
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Type</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead className="text-right">Qty</TableHead>
                      <TableHead className="text-right">Unit Price</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                      <TableHead>Job</TableHead>
                      <TableHead>Approved At</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {[...invoiceLineItems].reverse().map((li) => (
                      <TableRow key={li.id}>
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={LINE_TYPE_COLORS[li.type] ?? ""}
                          >
                            {li.type}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-sm max-w-[200px] truncate">
                          {li.description}
                        </TableCell>
                        <TableCell className="text-right">{li.quantity}</TableCell>
                        <TableCell className="text-right">{fmt(li.unitPrice)}</TableCell>
                        <TableCell className="text-right font-medium">{fmt(li.amount)}</TableCell>
                        <TableCell><JobLink jobId={li.jobId} /></TableCell>
                        <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                          {fmtDate(li.approvedAt)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </Layout>
  );
}
